default_language_version:
    python: python3.8

repos:
    # Automatically sort imports
    - repo: https://github.com/PyCQA/isort.git
      rev: 5.10.1
      hooks:
          - id: isort

    # Automatic source code formatting
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
            args: [--safe, --quiet]

    - repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
          - id: flake8

      # Syntax check and some basic flake8
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-merge-conflict
          - id: debug-statements

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.982
      hooks:
          - id: mypy
            args: [--python-version=3.10, --ignore-missing-imports]
            additional_dependencies: [types-python-dateutil]

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.0.0-alpha.1"
      hooks:
          - id: prettier

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: "v8.25.0"
      hooks:
          - id: eslint
